# Generated by Django 2.2.9 on 2021-05-04 11:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0003_auto_20210422_0946'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entry',
            name='completed',
        ),
        migrations.RemoveField(
            model_name='entry',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='entry',
            name='start_time',
        ),
        migrations.AddField(
            model_name='entry',
            name='day',
            field=models.CharField(default='Monday', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='entry',
            name='time_range',
            field=models.CharField(default='3.00 - 4.00', help_text='3.00 - 4.00', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='timetable',
            name='interval',
            field=models.CharField(default='10', help_text='Divided time by minutes.', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='timetable',
            name='start_time',
            field=models.TimeField(default=datetime.time(12, 5, 33, 162982)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='timetable',
            name='table_length',
            field=models.CharField(default='10', help_text='How many rows?', max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='entry',
            name='activity',
            field=models.CharField(max_length=50),
        ),
    ]
