# Generated by Django 2.2.9 on 2021-05-04 11:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0004_auto_20210504_1205'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entry',
            name='activity',
        ),
        migrations.CreateModel(
            name='EntryItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity', models.CharField(max_length=50)),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='timetable.Entry')),
            ],
        ),
    ]
