# Generated by Django 2.2.9 on 2021-05-04 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0005_auto_20210504_1217'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entry',
            name='time_range',
        ),
        migrations.AddField(
            model_name='entryitem',
            name='time_range',
            field=models.CharField(default='3.00 - 4.00', help_text='3.00 - 4.00', max_length=20),
            preserve_default=False,
        ),
    ]
