# Generated by Django 2.2.9 on 2021-05-08 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0007_auto_20210508_0342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timetable',
            name='start_time',
            field=models.TimeField(),
        ),
    ]
